### ISSUE TITLE
Cannot read property 'hostname' of undefined

### ISSUE THREAD

**Issue by x-qey** [talmobi/yt-search#12]
hi a new issue. Code:

> s.getTrack(`some spotify track id`)
            .then(async function (data) {
                let trackname = `${data.artists[0].name} - ${data.name} `
                let result = await yts(trackname)
                console.log(result)
            }, function (err) {
                console.error(err);
            });

Error:
`(node:15672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hostname' of undefined
    at e (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\dasu\dist\dasu.min.js:1:513)
    at Object.t [as req] (C:\Users\ocaku\OneDrive\Masaüstü\deneme\node_modules\dasu\dist\dasu.min.js:1:5491)
    at c (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\yt-search\dist\yt-search.min.js:1:6831)
    at i (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\yt-search\dist\yt-search.min.js:1:7656)
    at r (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\yt-search\dist\yt-search.min.js:1:1591)
    at new Promise (<anonymous>)
    at i (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\yt-search\dist\yt-search.min.js:1:1565)
    at t.exports (C:\Users\asd\OneDrive\Masaüstü\deneme\node_modules\yt-search\dist\yt-search.min.js:1:12159)
    at C:\Users\asd\OneDrive\Masaüstü\deneme\commands\music\play.js:72:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:15672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by talmobi** [comment]
Halåj,

What sort of system/environment are you running this on?

There may have been an issue of not fallbacking to a node env during a process which tries to resolve the current environment. Please try the updated v2.0.2 `npm install --save yt-search@latest`

**Comment by talmobi** [comment]
Hey, any updates on this?

**Comment by talmobi** [comment]
closing as inactive
