### ISSUE TITLE
Cannot find module dasu

### ISSUE THREAD

**Issue by Cammoy** [talmobi/yt-search#14]
Hi, I am experiencing an issue on vercel where it says in cannot find module dasu, I normally works locally. So it does not make sense. I am thinking its something to do the how that module is packaged.  

Do you have any ideas?

**Comment by Cammoy** [comment]
I will re try this on vercel now and let you know

**Comment by talmobi** [comment]
Halåj~

Which version are you using and which npm and node versions?

**Comment by talmobi** [comment]
Was this issue resolved?

**Comment by yareyaredesuyo** [comment]
I also got this error, when I used this library in next.js api and deploy it to vercel.
But works fine in local.

error:

```
2020-11-26T14:40:11.999Z	abf48a97-dc8e-41ac-8d19-1a45a4f3f425	
ERROR	Error: Cannot find module 'dasu'Require 
stack:- /var/task/node_modules/yt-search/dist/yt-search.min.js
- /var/task/.next/serverless/pages/api/youtubesingle.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)   
 at Function.Module._load (internal/modules/cjs/loader.js:687:27)   
 at Module.require (internal/modules/cjs/loader.js:903:19)    at require (internal/modules/cjs/helpers.js:74:18)   
 at s (/var/task/node_modules/yt-search/dist/yt-search.min.js:1:386)  
 at /var/task/node_modules/yt-search/dist/yt-search.min.js:1:560   
 at Object.1../util.js (/var/task/node_modules/yt-search/dist/yt-search.min.js:1:986)  
 at s (/var/task/node_modules/yt-search/dist/yt-search.min.js:1:526)   
 at r (/var/task/node_modules/yt-search/dist/yt-search.min.js:1:684)   
 at /var/task/node_modules/yt-search/dist/yt-search.min.js:1:701 {  code: 'MODULE_NOT_FOUND',
```

version:

```
"yt-search": "^2.5.0",
```

**Comment by talmobi** [comment]
Can you show the context of where it's being used in the code?

**Comment by yareyaredesuyo** [comment]
I use this library in the following way in nextjs lambda api.

pages/api/yt.ts

```ts
const yts = require("yt-search");

// https://github.com/talmobi/yt-search

import { NextApiRequest, NextApiResponse } from 'next'

export default async (req: NextApiRequest, res: NextApiResponse) => {

  const {
    query: { q },
  } = req;

  try {
    const r = await yts(q);
    res.status(200).json(r.videos);
  } catch (e) {
    console.log(e);
  }
}
```

**Comment by talmobi** [comment]
Thanks~

I can reproduce the issue, I'm looking into it.

**Comment by talmobi** [comment]
Update:

I haven't solved the issue yet, but it seems to be related to the lambda api is installed in vercel/next.

Even though vercel/next claims the lambdas use the package-json.lock and npm it is still failing to resolve the dependencies. I'm not sure if they are not downloaded at all or if it's a problem in how they resolve the dependencies.

Usually lamdas load all their data from a zip file direclty. But given that they apparently support npm modules and pacakge.json's they may be doing some tricky things behind the scenes that are failing. It is unclear as of yet.

The static pre-fetching works fine as you can see here: https://vercel-next-yt-search-test-hcxf6c9i7.vercel.app ( youtube video title inserted dynamically below the header )

**Comment by talmobi** [comment]
Update2:

I've been in contact with vercel support and trying to resolve the issue.

As a side note, here's an example of using yt-search in aws lambda: https://github.com/talmobi/yt-search-lambda

example api url: https://69v539djw3.execute-api.us-east-1.amazonaws.com/default/yt-search-api-lambda?search=superman+theme

**Comment by yareyaredesuyo** [comment]
@talmobi Thanks a lot!!!

**Comment by yareyaredesuyo** [comment]
I investigated the problem, and I found that changing package.json's main target from `dist/yt-search.min.js` to `dist/yt-search.js` and it worked.

Maybe related to uglify.js setting problem?

following is working image.

![スクリーンショット 2020-11-30 19 11 10](https://user-images.githubusercontent.com/31843888/100596735-d7b74300-333f-11eb-9788-282d7a32d3a8.png)

**Comment by talmobi** [comment]
@yareyaredesuyo wow! you're right! I can reproduce that it's working with the non-minified version (example: https://vercel-next-yt-search-test-127g4hwhu.vercel.app/api/hello).

Not sure what's going on but looks like perhaps uglifyJS is doing something that prevents the vercel/next lambda loader from recognizing or loading modules properly. Or something like that.

Not sure if it's an issue with uglifyJS or the vercel/next lambda loader.

Not sure what to do about it yet.

Nice catch!

**Comment by talmobi** [comment]
I'm leaning towards simply skipping the minified version altogether, regardless if it's an issue with uglify-js or vercel/next.

Thoughts or suggestions?

@yareyaredesuyo

**Comment by yareyaredesuyo** [comment]
I think, if you want to deliver both versions,  you should set not minified version for main, and minified version for another (like setting jsdelivr). And this is standard way, because it's a bit hard for debugging miinfied libs. 

Sample implementation: 
https://github.com/axios/axios/blob/master/package.json

```js
"main": "index.js",
"jsdelivr": "dist/axios.min.js",
"unpkg": "dist/axios.min.js",
```

And I think this is very tiny lib, not so much need for uglifying (also uglify is a bit obsolated, and you should think about switching using library like terser, ncc. switching example: https://github.com/twbs/bootstrap/pull/27813). 

refs:

https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified
