### ISSUE TITLE
TypeError: Cannot read property 'videos' of undefined

### ISSUE THREAD

**Issue by pollovolante** [talmobi/yt-search#26]
I've fixed this error yesterday using `npm install yt-search@latest` but today it reappeared
and this time I cannot fix it using `npm i` this is my code :
```js
const yts = require( 'yt-search' );
async function VideoUrl(nome){
    if(isUrl(nome)){
      const songInfo = await ytdl.getInfo(nome);
      return new Promise((resolve, reject) => {
          yts(songInfo.videoDetails.title, ( err, r ) => {
            if (err){
                  reject(err);
            }
              const videos = r.videos
              resolve({
                title:videos[0].title,                                  
                url:videos[0].url,
                duration:videos[0].timestamp,
                image:videos[0].image                    
                })
              })
            })
    }else{
      return new Promise((resolve, reject) => {
            yts(nome, ( err, r ) => {
              if (err){
                    reject(err);
                  }
                const videos = r.videos
                resolve({
                    title:videos[0].title,
                    url:videos[0].url,
                    duration:videos[0].timestamp,
                    image:videos[0].image
                })
                
            })
        });
}};
      const song =await VideoUrl(nome).catch(console.log)
``` 
FULL ERROR LOGS (I'm using heroku):
```
2020-08-23T13:43:44.767795+00:00 app[worker.1]: /app/commands/play.js:58
2020-08-23T13:43:44.767813+00:00 app[worker.1]:               const videos = r.videos
2020-08-23T13:43:44.767813+00:00 app[worker.1]:                                ^
2020-08-23T13:43:44.767814+00:00 app[worker.1]: 
2020-08-23T13:43:44.767814+00:00 app[worker.1]: TypeError: Cannot read property 'videos' of undefined
2020-08-23T13:43:44.767815+00:00 app[worker.1]:     at /app/commands/play.js:58:32
2020-08-23T13:43:44.767815+00:00 app[worker.1]:     at /app/node_modules/yt-search/dist/yt-search.min.js:1:7571
2020-08-23T13:43:44.767815+00:00 app[worker.1]:     at i (/app/node_modules/dasu/dist/dasu.min.js:1:4168)
2020-08-23T13:43:44.767816+00:00 app[worker.1]:     at Gunzip.<anonymous> (/app/node_modules/dasu/dist/dasu.min.js:1:2627)
2020-08-23T13:43:44.767816+00:00 app[worker.1]:     at Gunzip.emit (events.js:327:22)
2020-08-23T13:43:44.767816+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1220:12)
2020-08-23T13:43:44.767817+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I've also tryied to run my discord bot on localHost. Any Help?

**Comment by talmobi** [comment]
Hey!

Which version are you using specifically? Have you tried `yt-search@2.2.2`?

What search input are you using specifically?

Also it seems like in case of error you are only rejecting the promise but your code falls through where r will be undefined.

try using the `return` statement when you reject or resolve the promise.

**Comment by pollovolante** [comment]
> Hey!
> 
> Which version are you using specifically? Have you tried `yt-search@2.2.2`?
> 
> What search input are you using specifically?
> 
> Also it seems like in case of error you are only rejecting the promise but your code falls through where r will be undefined.
> 
> try using the `return` statement when you reject or resolve the promise.

thanks for reply.I'm using `yt-search@2.2.2`. The strainge thing is that now it is working although i haven't done anything. Yesterday all search inputs didn't work.

**Comment by talmobi** [comment]
Since your code fell through the promise rejection it's possible something like the networking was down since you were not handling the error. Not sure.

**Comment by pollovolante** [comment]
Ok thanks !
