### ISSUE TITLE
Error: yt-search: no query given

### ISSUE THREAD

**Issue by eitan07** [talmobi/yt-search#66]
Hello talmobi, the module doesn't work, but the cli version works great.
here's the log:
`Error: yt-search: no query given
    at search (C:\Users\user\Desktop\download++\node_modules\yt-search\dist\yt-search.js:174:21)       
    at _options.query (C:\Users\user\Desktop\download++\node_modules\yt-search\dist\yt-search.js:115:7)
    at new Promise (<anonymous>)
    at search (C:\Users\user\Desktop\download++\node_modules\yt-search\dist\yt-search.js:114:12)       
    at module.exports (C:\Users\user\Desktop\download++\node_modules\yt-search\dist\yt-search.js:94:10)
    at Object.<anonymous> (C:\Users\user\Desktop\download++\index.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)`

**Comment by talmobi** [comment]
Hello there~

Can you give a sample of the code you are using? It seems like you are not giving it a search term (which will produce this error if it's missing).

Have you seen some of the examples in the README?

**Comment by eitan07** [comment]
Sorry man, I thought it was a promise so I used .then () but now I realized I have to use callback as the second parameter.

Sorry if I wasted your time, thanks for replying quickly

**Comment by talmobi** [comment]
@eitan07 Hello there, not at all~

Promises are actually supported, but if you give it a callback as the second parameter, then it will default to using node-style callbacks. You can use Promises with .then or using the async/await keywords.

For example:

#### using .then()
```javascript
  yts( 'superman theme' ).then(function (result) {
    console.log( result )
  })
```

#### using async/await
```javascript
  let result = await yts( 'superman theme' );
  console.log( result )
```

If you find any bugs, please continue to report -- thanks~

**Comment by eitan07** [comment]
Thanks, I'll try it

**Comment by eitan07** [comment]
Yeah it's works!
I don't know why it wasn't worked before....

anyways thanks for helping me, have a great day
