### ISSUE TITLE
Error while searching with videoId "Cannot read properties of undefined (reading 'split')"

### ISSUE THREAD

**Issue by Laljaka** [talmobi/yt-search#68]
Hi!
I encountered an error while trying to get a video by it's id.

My code
```javascript
const yts = require('yt-search');

const video = await yts({ videoId: '62ezXENOuIA' });
console.log(video.title);
console.log(video.url);
console.log(video.thumbnail);
```

Error
```
TypeError: Cannot read properties of undefined (reading 'split')
    at _parseVideoInitialData (F:\NEWPAPAKA\repo\Meatbag-Music-Bot\node_modules\yt-search\dist\yt-search.js:788:47)
    at F:\NEWPAPAKA\repo\Meatbag-Music-Bot\node_modules\yt-search\dist\yt-search.js:730:9
    at i (F:\NEWPAPAKA\repo\Meatbag-Music-Bot\node_modules\dasu\dist\dasu.min.js:1:4223)
    at Gunzip.<anonymous> (F:\NEWPAPAKA\repo\Meatbag-Music-Bot\node_modules\dasu\dist\dasu.min.js:1:2627)
    at Gunzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Video id is from this url https://www.youtube.com/watch?v=62ezXENOuIA

Thank you in advance for the help!

**Comment by talmobi** [comment]
Thanks for reporting this~

It has been fixed in latest patch: `nom install yt-search@2.10.2`

The problem was that videos that have hidden their likes/dislikes ratio would fail to parse because the sentiment data would not be available. However the likes/dislikes were not being used anyway so it's a simple fix.

Maybe in future likes/dislikes will be added to the parsed results.
