### ISSUE TITLE
Dasu error or YT-search error?

### ISSUE THREAD

**Issue by Alixy-Mizuki** [talmobi/yt-search#69]
Here the Error.
```js
Type: unhandledRejection
Date: 2:17:03 PM

Reason: TypeError: Cannot assign to read only property 'log' of object '#<Object>'
    at Object.t [as req] (/home/runner/Frost/node_modules/dasu/dist/dasu.min.js:1:5764)
    at getSearchResults (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:311:9)
    at work (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:180:5)
    at search (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:177:3)
    at _options.query (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:115:7)
    at new Promise (<anonymous>)
    at search (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:114:12)
    at module.exports (/home/runner/Frost/node_modules/yt-search/dist/yt-search.js:94:10)
    at Object.run (/home/runner/Frost/commands/music/search.js:28:11)
```

I use 
Node `16.13.1`
yt-search `2.10.2`
bot is coded in Node.js / Javascript

the code i using is 
```js

const yts = require('yt-search');

module.exports = {    
  name: "search", 
  category: "music",
  async run ({ client, message, args, CatchErr, ErrMessage }) {
    try
    {
      const song = args.join(' ')

      console.log( yts(song) )
      //=================
    }
    catch(e)
    {
      CatchErr(e)
    }      
//=================
  }
}

**Comment by talmobi** [comment]
I'm unsure.

I've pushed a new update `yt-search@2.10.3` that should fix the error.

Also you remember to use `await` if you want the results from the Promise.

**Comment by Alixy-Mizuki** [comment]
> I'm unsure.
> 
> I've pushed a new update `yt-search@2.10.3` that should fix the error.
> 
> Also you remember to use `await` if you want the results from the Promise.

aight, thanks
